using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using HDScheduler.API.Models;
using HDScheduler.API.Repositories;
using HDScheduler.API.Services;
using HDScheduler.API.DTOs;

namespace HDScheduler.API.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class RecurringSessionsController : ControllerBase
{
    private readonly IPatientRepository _patientRepository;
    private readonly IHDScheduleRepository _scheduleRepository;
    private readonly IRecurringSessionService _recurringSessionService;
    private readonly ILogger<RecurringSessionsController> _logger;

    public RecurringSessionsController(
        IPatientRepository patientRepository,
        IHDScheduleRepository scheduleRepository,
        IRecurringSessionService recurringSessionService,
        ILogger<RecurringSessionsController> logger)
    {
        _patientRepository = patientRepository;
        _scheduleRepository = scheduleRepository;
        _recurringSessionService = recurringSessionService;
        _logger = logger;
    }

    /// <summary>
    /// Generate recurring sessions for a patient based on their HD Cycle
    /// </summary>
    [HttpPost("generate/{patientId}")]
    [Authorize(Roles = "Admin,Doctor,Nurse")]
    public async Task<ActionResult<ApiResponse<object>>> GenerateRecurringSessions(
        int patientId,
        [FromQuery] int daysAhead = 30,
        [FromQuery] int? slotId = null)
    {
        try
        {
            // Get patient
            var patient = await _patientRepository.GetByIdAsync(patientId);
            if (patient == null)
            {
                return NotFound(ApiResponse<object>.ErrorResponse("Patient not found"));
            }

            // Validate patient has HD Start Date and Cycle
            if (!patient.HDStartDate.HasValue)
            {
                return BadRequest(ApiResponse<object>.ErrorResponse("Patient must have HD Start Date set"));
            }

            if (string.IsNullOrEmpty(patient.HDCycle))
            {
                return BadRequest(ApiResponse<object>.ErrorResponse("Patient must have HD Cycle set"));
            }

            // Get current user info
            var userIdClaim = User.FindFirst("UserId")?.Value;
            var userNameClaim = User.FindFirst("Name")?.Value ?? "System";
            var userRoleClaim = User.FindFirst("http://schemas.microsoft.com/ws/2008/06/identity/claims/role")?.Value ?? "Admin";

            // Check if patient already has sessions
            var existingSessions = await _scheduleRepository.GetByPatientIdAsync(patientId);
            
            if (existingSessions.Any())
            {
                // Sessions already exist
                return Ok(ApiResponse<object>.SuccessResponse(new
                {
                    message = "Patient already has sessions scheduled",
                    existingSessionCount = existingSessions.Count,
                    sessions = existingSessions.Select(s => new
                    {
                        scheduleId = s.ScheduleID,
                        sessionDate = s.SessionDate,
                        status = s.SessionStatus
                    }).OrderBy(s => s.sessionDate).ToList()
                }));
            }

            // Determine slot ID
            int selectedSlotId = slotId ?? 1; // Default to Morning if not specified

            // Create the first base session for HD Start Date
            var baseSession = new HDSchedule
            {
                PatientID = patientId,
                SessionDate = patient.HDStartDate.Value,
                DryWeight = patient.DryWeight,
                HDStartDate = patient.HDStartDate,
                HDCycle = patient.HDCycle,
                HDFrequency = patient.HDFrequency,
                DialyserType = patient.DialyserType,
                DialyserModel = patient.DialyserModel,
                PrescribedDuration = patient.PrescribedDuration,
                PrescribedBFR = patient.PrescribedBFR,
                DialysatePrescription = patient.DialysatePrescription,
                SlotID = selectedSlotId,
                BedNumber = null, // To be assigned later
                SessionStatus = patient.HDStartDate.Value.Date == DateTime.Today ? "Active" : "Pre-Scheduled",
                IsAutoGenerated = false, // This is the base session
                IsDischarged = false,
                CreatedByStaffName = userNameClaim,
                CreatedByStaffRole = userRoleClaim,
                CreatedAt = DateTime.Now
            };

            // Create the base session
            var baseSessionId = await _scheduleRepository.CreateAsync(baseSession);
            baseSession.ScheduleID = baseSessionId;

            _logger.LogInformation("Created base session {ScheduleId} for patient {PatientId}", baseSessionId, patientId);

            // Generate recurring sessions
            var recurringSessionIds = await _recurringSessionService.GenerateRecurringSessions(baseSession, daysAhead);

            _logger.LogInformation("Generated {Count} recurring sessions for patient {PatientId}", 
                recurringSessionIds.Count, patientId);

            return Ok(ApiResponse<object>.SuccessResponse(new
            {
                message = "Recurring sessions generated successfully",
                baseSessionId,
                recurringSessionCount = recurringSessionIds.Count,
                totalSessions = recurringSessionIds.Count + 1,
                startDate = patient.HDStartDate.Value.ToString("yyyy-MM-dd"),
                hdCycle = patient.HDCycle,
                daysAhead
            }));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating recurring sessions for patient {PatientId}", patientId);
            return StatusCode(500, ApiResponse<object>.ErrorResponse($"An error occurred: {ex.Message}"));
        }
    }

    /// <summary>
    /// Delete all auto-generated sessions for a patient (keeps manual sessions)
    /// </summary>
    [HttpDelete("clear/{patientId}")]
    [Authorize(Roles = "Admin,Doctor")]
    public async Task<ActionResult<ApiResponse<object>>> ClearRecurringSessions(int patientId)
    {
        try
        {
            var sessions = await _scheduleRepository.GetByPatientIdAsync(patientId);
            var autoGeneratedSessions = sessions.Where(s => s.IsAutoGenerated).ToList();

            int deletedCount = 0;
            foreach (var session in autoGeneratedSessions)
            {
                var deleted = await _scheduleRepository.DeleteAsync(session.ScheduleID);
                if (deleted) deletedCount++;
            }

            return Ok(ApiResponse<object>.SuccessResponse(new
            {
                message = "Recurring sessions cleared",
                deletedCount
            }));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error clearing recurring sessions for patient {PatientId}", patientId);
            return StatusCode(500, ApiResponse<object>.ErrorResponse("An error occurred"));
        }
    }
}
