-- Migration: Add Session Status and Auto-Generation Tracking
-- Date: 2025-11-21
-- Description: Adds columns for managing pre-scheduled and recurring sessions

-- Add SessionStatus column
ALTER TABLE HDSchedule ADD COLUMN SessionStatus TEXT DEFAULT 'Active' CHECK (SessionStatus IN ('Pre-Scheduled', 'Active', 'Completed', 'Missed', 'Cancelled'));

-- Add IsAutoGenerated flag to track automatically created recurring sessions
ALTER TABLE HDSchedule ADD COLUMN IsAutoGenerated INTEGER DEFAULT 0;

-- Add ParentScheduleID to link recurring sessions back to original
ALTER TABLE HDSchedule ADD COLUMN ParentScheduleID INTEGER;

-- Update existing sessions to 'Active' or 'Completed' status
UPDATE HDSchedule SET SessionStatus = 'Completed' WHERE IsDischarged = 1;
UPDATE HDSchedule SET SessionStatus = 'Active' WHERE IsDischarged = 0;

-- Verify the columns were added
SELECT 'Session Status columns added successfully' AS Status;
