-- Demo Data Seed Script for HD Scheduler
-- Creates sample patients and HD sessions with recurring schedules

-- Insert Demo Patients
INSERT INTO Patients (Name, Age, Gender, Address, PhoneNumber1, PhoneNumber2, GuardianName, MRN, IsActive) VALUES
('John Smith', 58, 'Male', '123 Main St, City A', '555-0101', '555-0102', 'Mary Smith', 'MRN001', 1),
('Sarah Johnson', 62, 'Female', '456 Oak Ave, City B', '555-0201', NULL, 'Robert Johnson', 'MRN002', 1),
('Michael Brown', 45, 'Male', '789 Pine Rd, City C', '555-0301', '555-0302', NULL, 'MRN003', 1),
('Emily Davis', 71, 'Female', '321 Elm St, City D', '555-0401', '555-0402', 'David Davis', 'MRN004', 1),
('Robert Wilson', 53, 'Male', '654 Maple Dr, City E', '555-0501', NULL, NULL, 'MRN005', 1),
('Linda Martinez', 67, 'Female', '987 Cedar Ln, City F', '555-0601', '555-0602', 'Carlos Martinez', 'MRN006', 1),
('James Anderson', 49, 'Male', '147 Birch Way, City G', '555-0701', NULL, NULL, 'MRN007', 1),
('Patricia Taylor', 74, 'Female', '258 Spruce Ct, City H', '555-0801', '555-0802', 'William Taylor', 'MRN008', 1);

-- Get patient IDs (assuming they start from ID 32 onwards)
-- You may need to adjust these IDs based on your existing data

-- Active Sessions (Today - November 21, 2025)
-- Morning Slot (Slot 1) - MWF Patients
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
) VALUES
-- John Smith - Active session today (Thursday)
(32, '2025-11-21', 1, 1, 68.5, '2024-05-10', 'Tuesday, Thursday, Saturday (3x/week)', 4.0,
 'HI', 'Fresenius F8', 'AVF', 'Left radiocephalic', 350, 'Normal', 'Heparin', 2.5,
 'Active', 0, NULL, 'admin', 'Admin', 0),

-- Sarah Johnson - Active session today
(33, '2025-11-21', 1, 3, 72.0, '2023-08-15', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'LO', 'Baxter CT190', 'AVG', 'Right brachiocephalic', 400, 'K+ Free', 'Heparin', 3.0,
 'Active', 0, NULL, 'admin', 'Admin', 0),

-- Michael Brown - Active session today
(34, '2025-11-21', 1, 5, 81.2, '2024-01-20', 'Tuesday, Thursday, Saturday (3x/week)', 4.5,
 'HI', 'Fresenius F10', 'CVC', 'Right internal jugular', 380, 'Ca++', 'Without Heparin', 2.8,
 'Active', 0, NULL, 'admin', 'Admin', 0);

-- Afternoon Slot (Slot 2) - More active patients
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
) VALUES
-- Emily Davis - Active session today (Thursday)
(35, '2025-11-21', 2, 2, 65.3, '2023-11-05', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'LO', 'Nipro Elisio', 'AVF', 'Left brachiocephalic', 330, 'Normal', 'Heparin', 2.2,
 'Active', 0, NULL, 'admin', 'Admin', 0),

-- Robert Wilson - Active session today
(36, '2025-11-21', 2, 4, 76.8, '2024-03-12', 'Tuesday, Thursday, Saturday (3x/week)', 4.5,
 'HI', 'Fresenius FX80', 'AVG', 'Right brachiocephalic', 370, 'K+ Free', 'Heparin', 2.9,
 'Active', 0, NULL, 'admin', 'Admin', 0);

-- PRE-SCHEDULED SESSIONS for Tomorrow (November 22, 2025 - Friday)
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
) VALUES
-- Sarah Johnson - Pre-scheduled for Friday (MWF cycle)
(33, '2025-11-22', 1, NULL, 72.0, '2023-08-15', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'LO', 'Baxter CT190', 'AVG', 'Right brachiocephalic', 400, 'K+ Free', 'Heparin', 3.0,
 'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0),

-- Emily Davis - Pre-scheduled for Friday (MWF cycle)
(35, '2025-11-22', 2, NULL, 65.3, '2023-11-05', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'LO', 'Nipro Elisio', 'AVF', 'Left brachiocephalic', 330, 'Normal', 'Heparin', 2.2,
 'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0);

-- PRE-SCHEDULED SESSIONS for Saturday (November 23, 2025)
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
) VALUES
-- John Smith - Pre-scheduled for Saturday (TTS cycle)
(32, '2025-11-23', 1, NULL, 68.5, '2024-05-10', 'Tuesday, Thursday, Saturday (3x/week)', 4.0,
 'HI', 'Fresenius F8', 'AVF', 'Left radiocephalic', 350, 'Normal', 'Heparin', 2.5,
 'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0),

-- Michael Brown - Pre-scheduled for Saturday (TTS cycle)
(34, '2025-11-23', 1, NULL, 81.2, '2024-01-20', 'Tuesday, Thursday, Saturday (3x/week)', 4.5,
 'HI', 'Fresenius F10', 'CVC', 'Right internal jugular', 380, 'Ca++', 'Without Heparin', 2.8,
 'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0),

-- Robert Wilson - Pre-scheduled for Saturday (TTS cycle)
(36, '2025-11-23', 2, NULL, 76.8, '2024-03-12', 'Tuesday, Thursday, Saturday (3x/week)', 4.5,
 'HI', 'Fresenius FX80', 'AVG', 'Right brachiocephalic', 370, 'K+ Free', 'Heparin', 2.9,
 'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0);

-- PRE-SCHEDULED SESSIONS for Monday (November 24, 2025)
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
) VALUES
-- Sarah Johnson - Pre-scheduled for Monday (MWF cycle)
(33, '2025-11-24', 1, NULL, 72.0, '2023-08-15', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'LO', 'Baxter CT190', 'AVG', 'Right brachiocephalic', 400, 'K+ Free', 'Heparin', 3.0,
 'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0),

-- Emily Davis - Pre-scheduled for Monday (MWF cycle)
(35, '2025-11-24', 2, NULL, 65.3, '2023-11-05', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'LO', 'Nipro Elisio', 'AVF', 'Left brachiocephalic', 330, 'Normal', 'Heparin', 2.2,
 'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0),

-- Linda Martinez - Pre-scheduled for Monday (new patient, MWF cycle)
(37, '2025-11-24', 2, NULL, 69.7, '2024-09-20', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'HI', 'Fresenius F7', 'AVF', 'Right radiocephalic', 360, 'Normal', 'Heparin', 2.6,
 'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0);

-- COMPLETED SESSIONS from Previous Days (for history)
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, PreWeight, PostWeight,
    SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
) VALUES
-- Completed sessions from Tuesday (Nov 19)
(32, '2025-11-19', 1, 1, 68.5, '2024-05-10', 'Tuesday, Thursday, Saturday (3x/week)', 4.0,
 'HI', 'Fresenius F8', 'AVF', 'Left radiocephalic', 350, 'Normal', 'Heparin', 2.5, 71.0, 68.8,
 'Completed', 0, NULL, 'admin', 'Admin', 1),

(34, '2025-11-19', 1, 5, 81.2, '2024-01-20', 'Tuesday, Thursday, Saturday (3x/week)', 4.5,
 'HI', 'Fresenius F10', 'CVC', 'Right internal jugular', 380, 'Ca++', 'Without Heparin', 2.8, 84.0, 81.5,
 'Completed', 0, NULL, 'admin', 'Admin', 1),

-- Completed sessions from Monday (Nov 18)
(33, '2025-11-18', 1, 3, 72.0, '2023-08-15', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'LO', 'Baxter CT190', 'AVG', 'Right brachiocephalic', 400, 'K+ Free', 'Heparin', 3.0, 75.0, 72.2,
 'Completed', 0, NULL, 'admin', 'Admin', 1),

(35, '2025-11-18', 2, 2, 65.3, '2023-11-05', 'Monday, Wednesday, Friday (3x/week)', 4.0,
 'LO', 'Nipro Elisio', 'AVF', 'Left brachiocephalic', 330, 'Normal', 'Heparin', 2.2, 67.5, 65.5,
 'Completed', 0, NULL, 'admin', 'Admin', 1);

SELECT 'Demo data seeded successfully!' AS Status;
SELECT 'Created ' || COUNT(*) || ' demo patients' AS Result FROM Patients WHERE PatientID >= 32;
SELECT 'Created ' || COUNT(*) || ' HD sessions (Active: ' || 
       SUM(CASE WHEN SessionStatus = 'Active' THEN 1 ELSE 0 END) || 
       ', Pre-Scheduled: ' || SUM(CASE WHEN SessionStatus = 'Pre-Scheduled' THEN 1 ELSE 0 END) || 
       ', Completed: ' || SUM(CASE WHEN SessionStatus = 'Completed' THEN 1 ELSE 0 END) || ')' AS Result 
FROM HDSchedule WHERE PatientID >= 32;
