-- Add HD Sessions for Demo Patients with SessionStatus
-- Run this after migration 21 is complete

-- First, let's find our demo patient IDs
-- Demo patients have MRN like 'MRN00%'

-- Active Sessions (Today - November 21, 2025)
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-21', 1, 1, 68.5, '2024-05-10', 'Tuesday, Thursday, Saturday (3x/week)', 4.0,
    'HI', 'Fresenius F8', 'AVF', 'Left radiocephalic', 350, 'Normal', 'Heparin', 2.5,
    'Active', 0, NULL, 'admin', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN001'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-21');

INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-21', 1, 3, 72.0, '2023-08-15', 'Monday, Wednesday, Friday (3x/week)', 4.0,
    'LO', 'Baxter CT190', 'AVG', 'Right brachiocephalic', 400, 'K+ Free', 'Heparin', 3.0,
    'Active', 0, NULL, 'admin', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN002'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-21');

INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-21', 2, 5, 81.2, '2024-01-20', 'Tuesday, Thursday, Saturday (3x/week)', 4.5,
    'HI', 'Fresenius F10', 'CVC', 'Right internal jugular', 380, 'Ca++', 'Without Heparin', 2.8,
    'Active', 0, NULL, 'admin', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN003'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-21');

-- Pre-Scheduled Sessions (Tomorrow - Friday, Nov 22)
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-22', 1, NULL, 72.0, '2023-08-15', 'Monday, Wednesday, Friday (3x/week)', 4.0,
    'LO', 'Baxter CT190', 'AVG', 'Right brachiocephalic', 400, 'K+ Free', 'Heparin', 3.0,
    'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN002'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-22');

INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-22', 2, NULL, 65.3, '2023-11-05', 'Monday, Wednesday, Friday (3x/week)', 4.0,
    'LO', 'Nipro Elisio', 'AVF', 'Left brachiocephalic', 330, 'Normal', 'Heparin', 2.2,
    'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN004'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-22');

-- Pre-Scheduled Sessions (Saturday, Nov 23)
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-23', 1, NULL, 68.5, '2024-05-10', 'Tuesday, Thursday, Saturday (3x/week)', 4.0,
    'HI', 'Fresenius F8', 'AVF', 'Left radiocephalic', 350, 'Normal', 'Heparin', 2.5,
    'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN001'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-23');

INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-23', 1, NULL, 81.2, '2024-01-20', 'Tuesday, Thursday, Saturday (3x/week)', 4.5,
    'HI', 'Fresenius F10', 'CVC', 'Right internal jugular', 380, 'Ca++', 'Without Heparin', 2.8,
    'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN003'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-23');

-- Pre-Scheduled Sessions (Monday, Nov 24)
INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-24', 1, NULL, 72.0, '2023-08-15', 'Monday, Wednesday, Friday (3x/week)', 4.0,
    'LO', 'Baxter CT190', 'AVG', 'Right brachiocephalic', 400, 'K+ Free', 'Heparin', 3.0,
    'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN002'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-24');

INSERT INTO HDSchedule (
    PatientID, SessionDate, SlotID, BedNumber,
    DryWeight, HDStartDate, HDCycle, PrescribedDuration,
    DialyserType, DialyserModel, AccessType, AccessLocation,
    PrescribedBFR, DialysatePrescription, AnticoagulationType,
    UFGoal, SessionStatus, IsAutoGenerated, ParentScheduleID,
    CreatedByStaffName, CreatedByStaffRole, IsDischarged
)
SELECT 
    p.PatientID, '2025-11-24', 2, NULL, 65.3, '2023-11-05', 'Monday, Wednesday, Friday (3x/week)', 4.0,
    'LO', 'Nipro Elisio', 'AVF', 'Left brachiocephalic', 330, 'Normal', 'Heparin', 2.2,
    'Pre-Scheduled', 1, NULL, 'System', 'Admin', 0
FROM Patients p WHERE p.MRN = 'MRN004'
AND NOT EXISTS (SELECT 1 FROM HDSchedule WHERE PatientID = p.PatientID AND SessionDate = '2025-11-24');

-- Verify
SELECT 'Active Sessions Today: ' || COUNT(*) FROM HDSchedule WHERE SessionDate = '2025-11-21' AND SessionStatus = 'Active';
SELECT 'Pre-Scheduled Sessions: ' || COUNT(*) FROM HDSchedule WHERE SessionStatus = 'Pre-Scheduled';
SELECT 'Sessions by Date:';
SELECT SessionDate, COUNT(*) as SessionCount, SessionStatus 
FROM HDSchedule 
WHERE SessionDate >= '2025-11-21' AND SessionDate <= '2025-11-24'
GROUP BY SessionDate, SessionStatus
ORDER BY SessionDate;
